### Lambda Function
Short function which consist expression of logic     
No definition, directly used as expresssion and its inputs   
Syntax : 'lambda argument : expression'

In [1]:
import pandas as pd

In [2]:
# A list of tuples: (Iterarion, Accuracy)
models = [('I_1', 0.88), ('I_2', 0.92), ('I_3', 0.75), ('I_4', 0.81)]

# Sort by the second element (Accuracy)
# The lambda takes the tuple 'x' and returns 'x[1]' as the sorting key.
# Note that lambda is given as an expression. used inside sort function
models.sort(key=lambda x: x[1], reverse=True)

print(models)

[('I_2', 0.92), ('I_1', 0.88), ('I_4', 0.81), ('I_3', 0.75)]

In [3]:
text_data = ["  Hello World ", "AI is Cool", "  Python  "]

# Strip whitespace and convert to lower case in one go
clean_data = list(map(lambda s: s.strip().lower(), text_data))

print(clean_data)

['hello world', 'ai is cool', 'python']

**Use of lambda in dataframe**  
lambda functions can be quite handy in pandas dataframe, if there are some processing required in the data  
there could be scenario where pandas operations directly could not be possible or be ambiguous  
lambda functions can be used in such scneario

In [4]:
# Data with a field with a data structure as such
# The user action data contains the user events per user
data = {
    'user_id': [101, 102, 103],
    # Column contains a list of dictionaries
    'events': [
        [{'type': 'click', 'time': '10:00'}, {'type': 'view', 'time': '10:05'}],
        [{'type': 'click', 'time': '11:00'}, {'type': 'purchase', 'time': '11:15'}, {'type': 'view', 'time': '11:20'}],
        [{'type': 'scroll', 'time': '12:00'}]
    ]
}
user_data = pd.DataFrame(data)
user_data

   user_id                                             events
0      101  [{'type': 'click', 'time': '10:00'}, {'type': ...
1      102  [{'type': 'click', 'time': '11:00'}, {'type': ...
2      103              [{'type': 'scroll', 'time': '12:00'}]

In [5]:
# Create a new column 'is_purchaser' (Boolean)

# The lambda function checks if ANY item in the list 'x' 
# has the 'type' key equal to 'purchase'.
user_data['is_purchaser'] = user_data['events'].apply(lambda x: any(event['type'] == 'purchase' for event in x))

user_data

   user_id                                             events  is_purchaser
0      101  [{'type': 'click', 'time': '10:00'}, {'type': ...         False
1      102  [{'type': 'click', 'time': '11:00'}, {'type': ...          True
2      103              [{'type': 'scroll', 'time': '12:00'}]         False

In [6]:
temp_data = pd.DataFrame({
    'temp': [20, 35, 10, 45],
    'humidity': [50, 90, 20, 30]
})

temp_data

   temp  humidity
0    20        50
1    35        90
2    10        20
3    45        30

In [7]:
# Custom logic for "Threshold Level"
# apply this logic for each row and perform the check.
# Use of expression - similar to comprehensions

temp_data['risk'] = temp_data.apply(
    lambda row: "High" if row['temp'] > 40 or (row['temp'] > 30 and row['humidity'] > 80) else "Low", 
    axis=1
)

temp_data

   temp  humidity  risk
0    20        50   Low
1    35        90  High
2    10        20   Low
3    45        30  High

In [8]:
Index_Data = pd.read_csv ('Index.csv', parse_dates=['Date'], date_format="%d-%b-%y")
print (Index_Data.dtypes)

Index Name               str
Date          datetime64[us]
Open                 float64
High                 float64
Low                  float64
Close                float64
dtype: object

In [9]:
Index_Data.sort_values (by='Date', inplace=True)

# Calculate the minimum of the next 5 days' Lows (M_L)
# This is the lowest possible price in the next 5 days.
# Rolling function works as 'Backward looking' - This in combination with shift can be made into 'forward looking'.
Index_Data['next_5_low_min'] = Index_Data['Low'].rolling(window=5).min().shift(-5)

# Calculate the maximum of the next 5 days' Highs (M_H)
# This is the highest possible price in the next 5 days.
Index_Data['next_5_high_max'] = Index_Data['High'].rolling(window=5).max().shift(-5)
# Index_Data.to_csv ('Temp.csv', index=False, float_format='%.2f')

In [10]:
Index_Data['trend'] = Index_Data.apply(
    lambda row: (
        'Bullish' if row['next_5_low_min'] > row['Close'] else
        'Bearish' if row['next_5_high_max'] < row['Close'] else
        'Neutral'
    ),
    axis=1 
)

# Index_Data.to_csv ('Temp.csv', index=False, float_format='%.2f')
Index_Data

,Index Name,Date,Open,High,Low,Close,next_5_low_min,next_5_high_max,trend
248,NIFTY 50,2024-11-29,23927.15,24188.45,23927.15,24131.10,24008.65,24857.75,Neutral
247,NIFTY 50,2024-12-02,24140.85,24301.70,24008.65,24276.05,24280.00,24857.75,Bullish
246,NIFTY 50,2024-12-03,24367.50,24481.35,24280.00,24457.15,24295.55,24857.75,Neutral
245,NIFTY 50,2024-12-04,24488.75,24573.20,24366.30,24467.45,24295.55,24857.75,Neutral
244,NIFTY 50,2024-12-05,24539.15,24857.75,24295.55,24708.40,24510.65,24751.05,Neutral
...,...,...,...,...,...,...,...,...,...
4,NIFTY 50,2025-11-24,26122.80,26142.80,25912.15,25959.50,NaN,NaN,Neutral
3,NIFTY 50,2025-11-25,25998.50,26032.60,25857.50,25884.80,NaN,NaN,Neutral
2,NIFTY 50,2025-11-26,25842.95,26215.15,25842.95,26205.30,NaN,NaN,Neutral
1,NIFTY 50,2025-11-27,26261.25,26310.45,26141.90,26215.55,NaN,NaN,Neutral
0,NIFTY 50,2025-11-28,26237.45,26280.75,26172.40,26202.95,NaN,NaN,Neutral